# vim:sw=2:et:

os: linux
dist: xenial
language: elixir
notifications:
  email:
    recipients:
      - alerts@rabbitmq.com
    on_success: never
    on_failure: always
addons:
  apt:
    packages:
      - awscli
cache:
  apt: true
env:
  global:
    - secure: NPk7yFzpxl8ZhheQvf1MG3dWTQq+8o1Fp+XvrBWr3PiQAn8TWHmlmxAt74LlTqRpu8CXINCOpVUYNWF9Gl4gZ0HerV1Gobj0hrF8/PVO6Qz7bqRhcnXj1ax1q4CMjzqyBtt09Pd06Vmx/hgEOQys8+kimpaftIWfBREKyjlYSss=
    - secure: PjgBRIvkFXBaty94tOf4oomMSg9B9qdVLKmlb1o8DzE4KkCt2Cb3u00tqHYkvSzzgizSYsdff21TLrdQxw04aRtSVUIk2hqMt4tHbE9+sZL1Y8Cd75ZpjiSOYqnJtG0RbNxhTplCoyDOjaJWc9pjWgafHwHrZdo1wEgfzWDPWic=

    # $base_rmq_ref is used by rabbitmq-components.mk to select the
    # appropriate branch for dependencies.
    - base_rmq_ref=master

elixir:
  - '1.9'
otp_release:
  - '21.3'
  - '22.2'

install:
  # This project being an Erlang one (we just set language to Elixir
  # to ensure it is installed), we don't want Travis to run mix(1)
  # automatically as it will break.
  skip

script:
  # $current_rmq_ref is also used by rabbitmq-components.mk to select
  # the appropriate branch for dependencies.
  - make check-rabbitmq-components.mk
    current_rmq_ref="${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"
  - make xref
    current_rmq_ref="${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"
  - make tests
    current_rmq_ref="${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
