server:
  port: 8443
  ssl:
    bundle: spring-authorizationserver
  
spring:
  ssl:
    bundle:
      jks:
        spring-authorizationserver:
          key:
            alias: server-spring-tls
            password: foobar
          keystore:
            location: ../test/authnz-msg-protocols/spring/server_spring.jks
            password: foobar
            type: PKCS12
  security:
    oauth2:
      users:
        - username: rabbit_admin
          password: rabbit_admin 
          scopes: 
            - openid 
            - profile 
            - rabbitmq.tag:administrator
          audiencies: 
            - rabbitmq
      authorizationserver:
        client:
          producer:
            registration:
              provider: spring
              client-id: producer
              client-secret: "{noop}producer"
              authorization-grant-types: 
                - client_credentials
              client-authentication-methods:
                - client_secret_post              
              scopes: 
                - openid
                - profile
                - rabbitmq.tag:management
                - rabbitmq.configure:*/*
                - rabbitmq.read:*/*
                - rabbitmq.write:*/*
              client-name: producer
            token:
                access-token-format: reference
          rabbitmq_client_code:
            registration:
              provider: spring
              client-id: rabbitmq_client_code
              authorization-grant-types: 
                - authorization_code
              require-proof-key: true  
              client-authentication-methods:
                - none
              redirect-uris: 
                - "https://localhost:15671/js/oidc-oauth/login-callback.html"
              post-logout-redirect-uris:
                - "https://localhost:15671/"
              scopes: 
                - openid 
                - profile 
                - rabbitmq.tag:administrator
                - rabbitmq.tag:management
              client-name: rabbitmq_client_code

            