name: Spring Authorization Server docker image (make)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/authorization-server-make.yaml
      - selenium/authorization-server
  pull_request:
    paths:
      - .github/workflows/authorization-server-make.yaml
      - selenium/authorization-server

env:
  REGISTRY_IMAGE: pivotalrabbitmq/spring-authorization-server
  IMAGE_TAG: 0.0.11
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: selenium/authorization-server
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}
