# https://github.com/marketplace/actions/build-and-push-docker-images
name: OCI
on:
  push:
    paths:
      - 'deps/**'
      - 'escript/**'
      - 'packaging/**'
      - 'scripts/**'
      - Makefile
      - plugins.mk
      - rabbitmq-components.mk
env:
  GENERIC_UNIX_ARCHIVE: ${{ github.workspace }}/PACKAGES/rabbitmq-server-generic-unix-${{ github.sha }}.tar.xz
  RABBITMQ_VERSION: ${{ github.sha }}
  VERSION: ${{ github.sha }}
jobs:
  # This job will build two docker images (one with minimum required OTP, one with maximum supported OTP).
  # Each image will have two tags (one containing the Git commit SHA, one containing the branch name).
  #
  # For example, for Git commit SHA '1111aaa' and branch name 'main', the following four tags will be pushed to Dockerhub:
  # * 1111aaa-otp-min (image 1)
  # * main-otp-min (image 1)
  # * 1111aaa-otp-max (image 2)
  # * main-otp-max (image 2)
  build-publish-dev:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            # Build two images:
            # 1. with minimum required Erlang
            # 2. with maximum supported Erlang
            # Source of truth for released versions: https://www.rabbitmq.com/which-erlang.html
            # For Elixir: https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_cli/mix.exs#L14
            # As of June 2021:
            otp: ['23.2.1', '24.0.2']
            include:
            - otp: '23.2.1'
              otp_sha256: e7034e2cfe50d7570ac8f70ea7ba69ea013f10863043e25132f0a5d3d0d8d3a7
              elixir: '1.11.4'
              image_tag_suffix: '-otp-min'
            - otp: '24.0.2'
              otp_sha256: 4abca2cda7fc962ad65575e5ed834dd69c745e7e637f92cfd49f384a281d0f18
              elixir: '1.12.1'
              image_tag_suffix: '-otp-max'
    env:
      IMAGE_TAG_1: ${{ github.sha }}${{ matrix.image_tag_suffix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Erlang & Elixir
        uses: erlef/setup-beam@v1.7
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Build generic unix package
        run: |
          make package-generic-unix PROJECT_VERSION=${GITHUB_SHA}

      - name: Build container image
        working-directory: packaging/docker-image
        env:
          OTP_VERSION: ${{ matrix.otp }}
          OTP_SHA256: ${{ matrix.otp_sha256 }}
        run: |
          make dist SKIP_PGP_VERIFY=true

      - name: Login to DockerHub
        working-directory: packaging/docker-image
        run: |
          docker login \
            --username '${{ secrets.DOCKERHUB_USERNAME }}' \
            --password '${{ secrets.DOCKERHUB_PASSWORD }}'

      # Push the same image with two different tags:
      # 1. <git_commit_sha>-otp-[min|max]
      # 2. <branch_name>-otp-[min|max]
      - name: Push container image to DockerHub
        working-directory: packaging/docker-image
        env:
          IMAGE_TAG_SUFFIX: ${{ matrix.image_tag_suffix }}
        run: |
          make push IMAGE_TAG_2=${GITHUB_REF##*/}${IMAGE_TAG_SUFFIX}
