name: "Trigger a 4.1.x alpha release build"
on:
  workflow_dispatch:
  push:
    branches:
      - "v4.1.x"
    paths:
      - "deps/*/src/**"
      - 'deps/rabbitmq_management/priv/**'
      - ".github/workflows/**"
      - "rabbitmq-components.mk"
env:
  DEV_WORKFLOW_REPOSITORY: "rabbitmq/server-packages"
jobs:
  trigger_alpha_build:
    runs-on: ubuntu-latest
    steps:
      - name: Compute prerelease identifier from commit SHA
        run: echo "PRERELEASE_IDENTIFIER=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Trigger a 4.0.x alpha build in ${{ env.DEV_WORKFLOW_REPOSITORY }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MK_RELEASE_AUTOMATION_TOKEN }}
          repository: ${{ env.DEV_WORKFLOW_REPOSITORY }}
          event-type: "new_4.1.x_alpha"
          client-payload: |-
            {
              "release_repository": "${{ env.DEV_WORKFLOW_REPOSITORY }}",
              "release_description": "Commit: https://github.com/rabbitmq/rabbitmq-server/commit/${{ github.sha }}, pushed at: ${{ github.event.repository.pushed_at }}",
              "prerelease": true,
              "prerelease_kind": "alpha",
              "prerelease_identifier": "${{ env.PRERELEASE_IDENTIFIER }}",
              "release_title": "RabbitMQ ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}-alpha.${{ env.PRERELEASE_IDENTIFIER }} (from ${{ github.event.repository.pushed_at }})",
              "base_version": "${{ vars.SERVER_41_NEXT_PATCH_VERSION }}"
            }
