name: Generate Mixed Version Testing Artifacts
on:
  workflow_dispatch:
jobs:
  package-generic-unix:
    name: package-generic-unix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - erlang_major: "24"
          tag: v3.8.27
        - erlang_major: "24"
          tag: v3.9.13
        - erlang_major: "24"
          tag: v3.10.6
    timeout-minutes: 20
    steps:
    - name: Checkout Repository (Latest to get updated patches)
      uses: actions/checkout@v3
      with:
        path: latest

    - name: Checkout Repository (Secondary Umbrella tag)
      uses: actions/checkout@v3
      with:
        path: secondary-umbrella
        ref: ${{ matrix.tag }}

    - name: Apply Patch
      working-directory: secondary-umbrella
      run: |
        patch -p1 < ${{ github.workspace }}/latest/bazel/secondary-umbrella.patch
        git diff

    - name: Mount Bazel Cache
      uses: actions/cache@v3.0.5
      with:
        path: "/home/runner/repo-cache/"
        key: repo-cache-secondary-umbrella

    - name: Configure Bazel
      working-directory: secondary-umbrella
      run: |
        if [ -n "${{ secrets.BUILDBUDDY_API_KEY }}" ]; then
        cat << EOF >> user.bazelrc
          build:buildbuddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
        EOF
        fi
        cat << EOF >> user.bazelrc
          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PRIVATE
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-secondary-umbrella
          build:buildbuddy --repository_cache=/home/runner/repo-cache/
          build:buildbuddy --color=yes
          build:buildbuddy --disk_cache=

          build:buildbuddy --remote_download_toplevel
        EOF

        bazelisk info release

    - name: Build
      working-directory: secondary-umbrella
      run: |
        TAG=${{ matrix.tag }}
        VERSION=${TAG#v}
        sed -i"_orig" -E "/APP_VERSION/ s/3\.[0-9]+\.[0-9]+/${VERSION}/" rabbitmq.bzl
        bazelisk build :package-generic-unix \
          --config=rbe-${{ matrix.erlang_major }} \
          --verbose_failures

    - name: Rename the Artifact
      working-directory: secondary-umbrella
      run: |
        OUTPUT_DIR=${{ github.workspace }}/output
        mkdir ${OUTPUT_DIR}
        cp \
          bazel-bin/package-generic-unix.tar.xz \
          ${OUTPUT_DIR}/package-generic-unix-for-mixed-version-testing-${{ matrix.tag }}.tar.xz

    - name: Upload the archive to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: output
        DEST_DIR: secondary-umbrellas

    - name: Confirm public access
      run: |
        curl -LO https://rabbitmq-github-actions.s3.eu-west-1.amazonaws.com/secondary-umbrellas/package-generic-unix-for-mixed-version-testing-${{ matrix.tag }}.tar.xz
