name: Test Windows
on:
  push:
    paths:
      - 'deps/**'
      - 'scripts/**'
      - Makefile
      - plugins.mk
      - rabbitmq-components.mk
      - .bazelrc
      - .bazelversion
      - BUILD.*
      - '*.bzl'
      - '*.bazel'
      - .github/workflows/test-windows.yaml
jobs:
  test:
    name: Test Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        #! - "23"
        - "24"
    timeout-minutes: 120
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.4.0
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
        elixir-version: 1.12.3
    #! - name: MOUNT BAZEL CACHE
    #!   uses: actions/cache@v1
    #!   with:
    #!     path: "/home/runner/repo-cache/"
    #!     key: repo-cache
    - name: CONFIGURE BAZEL
      shell: bash
      run: |
        ERL_PATH="$(which erl)"
        IEX_PATH="$(which iex)"
        cat << EOF >> user.bazelrc
          startup --windows_enable_symlinks
          build --enable_runfiles

          build:buildbuddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PUBLIC
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-windows-${{ matrix.erlang_version }}
          # build:buildbuddy --repository_cache=/home/runner/repo-cache/
          build:buildbuddy --color=yes
          build:buildbuddy --disk_cache=

          build --@rules_erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@rules_erlang//:erlang_home="${ERL_PATH/\/bin\/erl/}"
          build --//:elixir_home="${IEX_PATH/\/bin\/iex/}"
        EOF

        bazelisk info release
    - name: RUN TESTS
      run: bazelisk test //... --config=buildbuddy --test_tag_filters=-exclusive,-aws,-bats,-starts-background-broker --build_tests_only --verbose_failures
