name: Test
on:
  push:
    paths:
      - 'deps/**'
      - 'scripts/**'
      - Makefile
      - plugins.mk
      - rabbitmq-components.mk
      - .bazelrc
      - .bazelversion
      - BUILD.*
      - '*.bzl'
      - '*.bazel'
      - .github/workflows/test.yaml
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        - "23"
        - "24"
        include:
        - erlang_version: "23"
          rbe_default_branch: linux-erlang-23.3
        - erlang_version: "24"
          rbe_default_branch: linux-erlang-24.1
    timeout-minutes: 120
    steps:
    - name: CHECKOUT REPOSITORY
<<<<<<< HEAD
      uses: actions/checkout@v2.3.4
=======
      uses: actions/checkout@v2.4.0
    - name: SELECT ERLANG VERSION
      run: |
        sudo npm install --global --silent @bazel/buildozer
        echo "$(cat WORKSPACE.bazel | npx buildozer 'set branch "${{ matrix.rbe_default_branch }}"' -:rbe_default)" > WORKSPACE.bazel
        git diff
>>>>>>> 92068f481c (Use externailzed rbe config in bazel)
    - name: CONFIGURE BAZEL
      run: |
        cat << EOF >> user.bazelrc
          build:buildbuddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PUBLIC
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-${{ matrix.erlang_version }}

          build:rbe --@bazel-erlang//:erlang_version=${{ matrix.erlang_version }}
        EOF
    #! - name: Setup tmate session
    #!   uses: mxschmitt/action-tmate@v3
    - name: RUN TESTS
      run: |
        bazelisk test //... \
          --config=rbe \
          --test_tag_filters=-exclusive,-aws,-mixed-version-cluster \
          --verbose_failures
  test-exclusive:
    name: Test (Exclusive Tests)
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        erlang_version:
        - "23"
        - "24"
    timeout-minutes: 60
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.3.4
    - name: CONFIGURE OTP & ELIXIR
      uses: erlef/setup-beam@v1.7
      with:
        otp-version: ${{ matrix.erlang_version }}
        elixir-version: 1.11.4
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        ELIXIR_HOME="$(dirname $(dirname $(which iex)))"
        cat << EOF >> user.bazelrc
          build:buildbuddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PRIVATE
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-exclusive-${{ matrix.erlang_version }}

          build --@bazel-erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@bazel-erlang//:erlang_home=${ERLANG_HOME}
          build --//:elixir_home=${ELIXIR_HOME}
        EOF
    #! - name: Setup tmate session
    #!   uses: mxschmitt/action-tmate@v3
    - name: RUN EXCLUSIVE TESTS
      run: |
        bazelisk test //... \
          --config=buildbuddy \
          --test_tag_filters=exclusive,-aws,-mixed-version-cluster \
          --build_tests_only \
          --test_env RABBITMQ_CT_HELPERS_DELETE_UNUSED_NODES=true \
          --verbose_failures
