name: Test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        erlang_version:
        - "23.1"
        - "22.3"
    timeout-minutes: 20
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2
    - name: CONFIGURE OTP & ELIXIR
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
        # https://github.com/elixir-lang/elixir/releases
        elixir-version: 1.10.4
    - name: INSTALL BAZELISK
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: RUN TESTS
      run: |
        erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
        mix --version

        echo "${{ secrets.BAZELRC_CONTENTS }}" > .bazelrc
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        ELIXIR_HOME="$(dirname $(dirname $(which iex)))"
        "${GITHUB_WORKSPACE}/bin/bazel" test //... \
          --//bazel_erlang:erlang_home=${ERLANG_HOME} \
          --//bazel_erlang:elixir_home=${ELIXIR_HOME} \
          --//bazel_erlang:mix_archives=/home/runner/.mix/archives \
          --test_tag_filters="erlang-${{ matrix.erlang_version }}" \
          --build_tests_only \
          --test_verbose_timeout_warnings \
          --verbose_failures
