name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        - "23"
        - "24"
    timeout-minutes: 120
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.3.4
    - name: CONFIGURE BAZEL
      run: |
        echo "${{ secrets.BUILDBUDDY_CERT }}" > buildbuddy-cert.pem
        echo "${{ secrets.BUILDBUDDY_KEY }}" > buildbuddy-key.pem
        cat << EOF >> user.bazelrc
          build:buildbuddy --tls_client_certificate=buildbuddy-cert.pem
          build:buildbuddy --tls_client_key=buildbuddy-key.pem

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PUBLIC
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-${{ matrix.erlang_version }}
        EOF
    #! - name: Setup tmate session
    #!   uses: mxschmitt/action-tmate@v3
    - name: RUN TESTS
      run: |
        bazelisk test //... \
          --config=rbe-${{ matrix.erlang_version }} \
          --test_tag_filters=-exclusive,-aws \
          --verbose_failures
  test-exclusive:
    name: Test (Exclusive Tests)
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        erlang_version:
        - "23"
        - "24"
    timeout-minutes: 60
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.3.4
    - name: CONFIGURE OTP & ELIXIR
      uses: erlef/setup-beam@v1.7
      with:
        otp-version: ${{ matrix.erlang_version }}
        elixir-version: 1.11.4
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        ELIXIR_HOME="$(dirname $(dirname $(which iex)))"
        echo "${{ secrets.BUILDBUDDY_CERT }}" > buildbuddy-cert.pem
        echo "${{ secrets.BUILDBUDDY_KEY }}" > buildbuddy-key.pem
        cat << EOF >> user.bazelrc
          build:buildbuddy --tls_client_certificate=buildbuddy-cert.pem
          build:buildbuddy --tls_client_key=buildbuddy-key.pem

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PRIVATE
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-exclusive-${{ matrix.erlang_version }}

          build --@bazel-erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@bazel-erlang//:erlang_home=${ERLANG_HOME}
          build --//:elixir_home=${ELIXIR_HOME}
        EOF
    #! - name: Setup tmate session
    #!   uses: mxschmitt/action-tmate@v3
    - name: RUN EXCLUSIVE TESTS
      run: |
        bazelisk test //... \
          --config=buildbuddy \
          --test_tag_filters=exclusive,-aws \
          --build_tests_only \
          --test_env RABBITMQ_CT_HELPERS_DELETE_UNUSED_NODES=true \
          --verbose_failures
