name: Update Bazel RBE Images
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-rbe-images:
    name: Update Bazel RBE Images
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        erlang_version:
        - "23.3"
        - "24.0"
        include:
        - erlang_version: "23.3"
          short_version: "23"
        - erlang_version: "24.0"
          short_version: "24"
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.3.4
    - name: UPDATE RBE IMAGE SHA
      env:
        IMAGE: pivotalrabbitmq/rabbitmq-server-buildenv
        TAG: linux-erlang-${{ matrix.erlang_version }}
      run: |
        # buildbuddy caches the container image, so we must use a specific sha to ensure
        # the latest is used
        echo "Retrieving current digest for ${IMAGE}:${TAG}"
        DIGEST="$(skopeo inspect --format '{{.Digest}}' docker://${IMAGE}:${TAG})"
        echo "Will use ${IMAGE}@${DIGEST}"
        sudo npm install --global --silent @bazel/buildozer
        npx buildozer \
          "dict_set exec_properties container-image:docker://${IMAGE}@${DIGEST}" \
          //:erlang_${{ matrix.short_version }}_platform || test $? -eq 3
    - name: CREATE PULL REQUEST
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: Adopt latest rabbitmq-server-buildenv:linux-erlang-${{ matrix.erlang_version }} for RBE
        commit-message: |
          Use latest rabbitmq-server-buildenv:linux-erlang-${{ matrix.erlang_version }}

          for remote build execution (RBE) with BuildBuddy
        labels: |
          backport-v3.9.x
          backport-v3.8.x
        branch: bump-rbe-image-${{ matrix.short_version }}
        delete-branch: true
