name: Update rbe-erlang-platform
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-rbe-images:
    name: Update rbe-erlang-platform
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        erlang_version:
        - "23.3"
        - "24.3"
        include:
        - erlang_version: "23.3"
          short_version: "23"
        - erlang_version: "24.3"
          short_version: "24"
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3
      with:
        path: rabbitmq-server
    - name: CHECKOUT rbe-erlang-platform REPOSITORY
      uses: actions/checkout@v3
      with:
        path: rbe-erlang-platform
        repository: rabbitmq/rbe-erlang-platform
        ref: linux-erlang-${{ matrix.erlang_version }}
    - name: DETERMINE LATEST COMMIT
      id: find-commit
      working-directory: rbe-erlang-platform
      run: |
        echo "::set-output name=SHA::$(git rev-parse HEAD)"
    - name: UPDATE rbe-erlang-platform COMMIT
      working-directory: rabbitmq-server
      run: |
        sudo npm install --global --silent @bazel/buildozer
        echo "$(cat WORKSPACE.bazel | npx buildozer 'set commit "${{ steps.find-commit.outputs.SHA }}"' -:rbe_${{ matrix.short_version }})" > WORKSPACE.bazel
        git diff
    - name: CREATE PULL REQUEST
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        title: Adopt latest rabbitmq-server-buildenv:linux-erlang-${{ matrix.erlang_version }} for RBE
        path: rabbitmq-server
        commit-message: |
          Use latest rbe-erlang-platform/linux-erlang-${{ matrix.erlang_version }}

          for remote build execution (RBE) with BuildBuddy
        labels: |
          backport-v3.10.x
          backport-v3.9.x
          backport-v3.8.x
        branch: bump-rbe-${{ matrix.short_version }}
        delete-branch: true
