name: Update OTP Versions for OCI Workflow
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-rbe-images:
    name: Update OTP Versions
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        erlang_version:
        - "24.0"
        include:
        - erlang_version: "24.0"
          image_tag_suffix: 'otp-max'
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.3.4
    - name: DETERMINE LATEST PATCH & SHA
      id: fetch-version
      run: |
        TAG_NAME=$(curl -s GET https://api.github.com/repos/erlang/otp/tags \
          | jq -r 'map(select(.name | contains("OTP-${{ matrix.erlang_version }}"))) | first | .name')

        wget --continue --quiet --output-document="/tmp/OTP.tar.gz" "https://github.com/erlang/otp/archive/${TAG_NAME}.tar.gz" && \
        SHA=$(shasum -a 256 "/tmp/OTP.tar.gz" | awk '{print $1}')

        echo "::set-output name=VERSION::${TAG_NAME#OTP-}"
        echo "::set-output name=SHA::${SHA}"
    - name: MODIFY VERSION FILE
      run: |
        echo "Updating packaging/docker-image/${{ matrix.image_tag_suffix }}.yaml with:"
        echo "  otp -> ${{ steps.fetch-version.outputs.VERSION }}"
        echo "  otp_sha256 -> ${{ steps.fetch-version.outputs.SHA }}"

        FILE=packaging/docker-image/otp-versions/${{ matrix.image_tag_suffix }}.yaml
        sed -i "s/otp: .*/otp: '${{ steps.fetch-version.outputs.VERSION }}'/" $FILE
        sed -i "s/otp_sha256: .*/otp_sha256: ${{ steps.fetch-version.outputs.SHA }}/" $FILE

        set -x
        git diff
    - name: CREATE PULL REQUEST
      uses: peter-evans/create-pull-request@v3
      with:
        title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }} for OCI workflow
        labels: |
          backport-v3.9.x
          backport-v3.8.x
        branch: bump-otp-for-oci
        delete-branch: true
